In [1]:
print("hello world")

hello world


In [2]:
#create an array

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
np

NameError: name 'np' is not defined

In [5]:
numpy.__version__

NameError: name 'numpy' is not defined

In [6]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ---------------------------------------- 61.2/61.2 kB 3.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.4/15.8 MB 11.5 MB/s eta 0:00:02
   - -------------------------------------- 0.8/15.8 MB 12.0 MB/s eta 0:00:02
   --- ------------------------------------ 1.4/15.8 MB 11.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.7/15.8 MB 10.6 MB/s eta 0:00:02
   ------ --------------------------------- 2.5/15.8 MB 11.2 MB/s eta 0:00:02
   ------- -------------------------------- 2.9/15.8 MB 10.8 MB/s eta 0:00:02
   -------- ------------------------------- 3.2/15.8 MB 10.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.7/15.8 MB 10.4 MB/s eta 0:00:02
   ---------- ----------------------------- 4.3/15.8 MB 10.1 MB/s eta 0:00:0

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [7]:
import numpy as np

In [8]:
np

<module 'numpy' from 'C:\\Users\\naniv\\AppData\\Roaming\\Python\\Python311\\site-packages\\numpy\\__init__.py'>

In [9]:
# create an array

In [10]:
np.array[10,20,30,55]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [11]:
np.array([10,20,66])

array([10, 20, 66])

In [12]:
np.range(5)

AttributeError: module 'numpy' has no attribute 'range'

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [1]:
np.array([[]])

NameError: name 'np' is not defined

In [2]:
b=np.array([[]])

NameError: name 'np' is not defined

In [3]:
np

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
c=np.array([[]])

In [6]:
c

array([], shape=(1, 0), dtype=float64)

In [7]:
np.mean(c)

C:\Users\naniv\AppData\Roaming\Python\Python311\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\naniv\AppData\Roaming\Python\Python311\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


nan

In [8]:
np.ones((2))

array([1., 1.])

In [9]:
np.ones((2,2,3))  

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
a = np.array([[5,10,15],
              [20,25,30],
              [35,40,45]])

In [11]:
np.mean(a)

25.0

In [12]:
np.std

<function std at 0x00000224FE7249F0>

In [13]:
np.std(a)

12.909944487358056

In [14]:
np.min(a)

5

In [15]:
np.max(a)

45

In [16]:
np.min(a,axis=0)

array([ 5, 10, 15])

In [17]:
np.max(a,axis=0)

array([35, 40, 45])

In [18]:
np.mean(a,axis=1)

array([10., 25., 40.])

In [19]:
np.max(a,axis=1)

array([15, 30, 45])